openapi: 3.0.3
info:
  title: State Pension
  contact: {}
  version: '1.0'
servers:
  - url: https://api.service.hmrc.gov.uk/
    variables: {}
paths:
  /state-pension/ni/{nino}:
    get:
      tags:
        - state-pension
      summary: Get State Pension statement
      description: Returns a State Pension statement
      operationId: GetStatePensionstatement
      parameters:
        - name: nino
          in: path
          description: A valid National Insurance number
          required: true
          style: simple
          schema:
            type: string
            example: QQ123456A
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/StatePensionNiresponse'
                  - example:
                      earningsIncludedUpTo: 2015-04-05
                      amounts:
                        protectedPayment: false
                        current:
                          weeklyAmount: 133.41
                          monthlyAmount: 580.1
                          annualAmount: 6961.14
                        forecast:
                          yearsToWork: 3
                          weeklyAmount: 146.76
                          monthlyAmount: 638.14
                          annualAmount: 7657.73
                        maximum:
                          yearsToWork: 3
                          gapsToFill: 2
                          weeklyAmount: 155.65
                          monthlyAmount: 676.8
                          annualAmount: 8121.59
                        cope:
                          weeklyAmount: 0
                          monthlyAmount: 0
                          annualAmount: 0
                        starting:
                          weeklyAmount: 130.05
                          monthlyAmount: 565.49
                          annualAmount: 6785.82
                        oldRules:
                          basicStatePension: 119.3
                          additionalStatePension: 10.75
                          graduatedRetirementBenefit: 0
                        newRules:
                          grossStatePension: 130.05
                          rebateDerivedAmount: 0
                      pensionAge: 64
                      pensionDate: 2018-07-06
                      finalRelevantYear: 2017-18
                      numberOfQualifyingYears: 30
                      pensionSharingOrder: false
                      currentWeeklyPensionAmount: 155.65
                      reducedRateElection: false
                      statePensionAgeUnderConsideration: false
                      _links:
                        self:
                          href: /state-pension/ni/QQ123456A
              examples:
                Regular:
                  description: Regular response
                  value:
                    earningsIncludedUpTo: 2015-04-05
                    amounts:
                      protectedPayment: false
                      current:
                        weeklyAmount: 133.41
                        monthlyAmount: 580.1
                        annualAmount: 6961.14
                      forecast:
                        yearsToWork: 3
                        weeklyAmount: 146.76
                        monthlyAmount: 638.14
                        annualAmount: 7657.73
                      maximum:
                        yearsToWork: 3
                        gapsToFill: 2
                        weeklyAmount: 155.65
                        monthlyAmount: 676.8
                        annualAmount: 8121.59
                      cope:
                        weeklyAmount: 0
                        monthlyAmount: 0
                        annualAmount: 0
                      starting:
                        weeklyAmount: 130.05
                        monthlyAmount: 565.49
                        annualAmount: 6785.82
                      oldRules:
                        basicStatePension: 119.3
                        additionalStatePension: 10.75
                        graduatedRetirementBenefit: 0
                      newRules:
                        grossStatePension: 130.05
                        rebateDerivedAmount: 0
                    pensionAge: 64
                    pensionDate: 2018-07-06
                    finalRelevantYear: 2017-18
                    numberOfQualifyingYears: 30
                    pensionSharingOrder: false
                    currentWeeklyPensionAmount: 155.65
                    reducedRateElection: false
                    statePensionAgeUnderConsideration: false
                    _links:
                      self:
                        href: /state-pension/ni/QQ123456A
                RegularReducedRateElection:
                  description: Regular (Reduced Rate Election) response
                  value:
                    earningsIncludedUpTo: 2015-04-05
                    amounts:
                      protectedPayment: false
                      current:
                        weeklyAmount: 133.41
                        monthlyAmount: 580.1
                        annualAmount: 6961.14
                      forecast:
                        yearsToWork: 3
                        weeklyAmount: 146.76
                        monthlyAmount: 638.14
                        annualAmount: 7657.73
                      maximum:
                        yearsToWork: 3
                        gapsToFill: 2
                        weeklyAmount: 155.65
                        monthlyAmount: 676.8
                        annualAmount: 8121.59
                      cope:
                        weeklyAmount: 0
                        monthlyAmount: 0
                        annualAmount: 0
                      starting:
                        weeklyAmount: 130.05
                        monthlyAmount: 565.49
                        annualAmount: 6785.82
                      oldRules:
                        basicStatePension: 119.3
                        additionalStatePension: 10.75
                        graduatedRetirementBenefit: 0
                      newRules:
                        grossStatePension: 130.05
                        rebateDerivedAmount: 0
                    pensionAge: 64
                    pensionDate: 2018-07-06
                    finalRelevantYear: 2017-18
                    numberOfQualifyingYears: 30
                    pensionSharingOrder: false
                    currentWeeklyPensionAmount: 155.65
                    reducedRateElection: true
                    reducedRateElectionCurrentWeeklyAmount: 133.41
                    statePensionAgeUnderConsideration: false
                    _links:
                      self:
                        href: /state-pension/ni/QQ123456A
                Exclusion:
                  description: Exclusion response
                  value:
                    exclusionReasons:
                      - AmountDissonance
                    pensionAge: 66
                    pensionDate: 2021-05-16
                    statePensionAgeUnderConsideration: false
                    _links:
                      self:
                        href: /state-pension/ni/QQ123456A
        '400':
          description: 'Bad Request'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: ERROR_NINO_INVALID
              examples:
                InvalidNino:
                  description: Invalid NINO
                  value:
                    code: ERROR_NINO_INVALID
                BadRequest:
                  description: Bad Request
                  value:
                    code: BAD_REQUEST
        '401':
          description: 'Unauthorised'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: UNAUTHORIZED
              examples:
                Unauth:
                  description: Unauthorized
                  value:
                    code: UNAUTHORIZED
        '403':
          description: 'Forbidden'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: EXCLUSION_MANUAL_CORRESPONDENCE
              examples:
                ExcManCor:
                  description: Manual Correspondence exclusion, the customer cannot be served digitally and needs to contact HMRC
                  value:
                    code: EXCLUSION_MANUAL_CORRESPONDENCE
                ExcDead:
                  description: Death recorded, the customer needs to contact the National Insurance Helpline
                  value:
                    code: EXCLUSION_DEAD
                ExcCopePro:
                  description: Cope data has an open work item meaning that the customer cannot enter the service and must come back at a later date.
                  value:
                    code: EXCLUSION_COPE_PROCESSING
                ExcCopeProFail:
                  description: Cope data has a closed work item against it meaning that the customer cannot enter the service and is advised to contact DWP.
                  value:
                    code: EXCLUSION_COPE_PROCESSING_FAILED
        '404':
          description: 'Not Found'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: NOT_FOUND
              examples:
                NotFound:
                  description: Resource not found
                  value:
                    code: NOT_FOUND
        '406':
          description: 'Not Acceptable'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: ACCEPT_HEADER_INVALID
              examples:
                NotAcceptable:
                  description: Accept header is missing or invalid
                  value:
                    code: ACCEPT_HEADER_INVALID
        '500':
          description: 'Server Error'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: INTERNAL_SERVER_ERROR
              examples:
                InternalServerError:
                  description: Internal Server Error
                  value:
                    code: INTERNAL_SERVER_ERROR
      deprecated: false
      security:
        - User-Restricted:
            - read:state-pension
  /state-pension/pd/ni/{nino}:
    get:
      tags:
        - state-pension
      summary: Get State Pension Dashboard data
      description: Returns a State Pension Dashboard data. ** DOCUMENTATION ONLY **
      operationId: GetStatePensionDashboarddata
      parameters:
        - name: nino
          in: path
          description: A valid National Insurance number
          required: true
          style: simple
          schema:
            type: string
            example: QQ123456A
      responses:
        '200':
          description: ''
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/StatePensionPdNiresponse'
                  - example:
                      earningsIncludedUpTo: 2015-04-05
                      amounts:
                        protectedPayment: false
                        current:
                          weeklyAmount: 133.41
                          monthlyAmount: 580.1
                          annualAmount: 6961.14
                        forecast:
                          yearsToWork: 3
                          weeklyAmount: 146.76
                          monthlyAmount: 638.14
                          annualAmount: 7657.73
                        maximum:
                          yearsToWork: 3
                          gapsToFill: 2
                          weeklyAmount: 155.65
                          monthlyAmount: 676.8
                          annualAmount: 8121.59
                        cope:
                          weeklyAmount: 0
                          monthlyAmount: 0
                          annualAmount: 0
                        starting:
                          weeklyAmount: 130.05
                          monthlyAmount: 565.49
                          annualAmount: 6785.82
                        oldRules:
                          basicStatePension: 119.3
                          additionalStatePension: 10.75
                          graduatedRetirementBenefit: 0
                        newRules:
                          grossStatePension: 130.05
                          rebateDerivedAmount: 0
                      pensionAge: 64
                      pensionDate: 2018-07-06
                      finalRelevantYear: 2017-18
                      numberOfQualifyingYears: 30
                      pensionSharingOrder: false
                      currentWeeklyPensionAmount: 155.65
                      reducedRateElection: false
                      statePensionAgeUnderConsideration: false
                      _links:
                        self:
                          href: /state-pension/pd/ni/QQ123456A
              examples:
                Regular:
                  description: Regular response
                  value:
                    earningsIncludedUpTo: 2015-04-05
                    amounts:
                      protectedPayment: false
                      current:
                        weeklyAmount: 133.41
                        monthlyAmount: 580.1
                        annualAmount: 6961.14
                      forecast:
                        yearsToWork: 3
                        weeklyAmount: 146.76
                        monthlyAmount: 638.14
                        annualAmount: 7657.73
                      maximum:
                        yearsToWork: 3
                        gapsToFill: 2
                        weeklyAmount: 155.65
                        monthlyAmount: 676.8
                        annualAmount: 8121.59
                      cope:
                        weeklyAmount: 0
                        monthlyAmount: 0
                        annualAmount: 0
                      starting:
                        weeklyAmount: 130.05
                        monthlyAmount: 565.49
                        annualAmount: 6785.82
                      oldRules:
                        basicStatePension: 119.3
                        additionalStatePension: 10.75
                        graduatedRetirementBenefit: 0
                      newRules:
                        grossStatePension: 130.05
                        rebateDerivedAmount: 0
                    pensionAge: 64
                    pensionDate: 2018-07-06
                    finalRelevantYear: 2017-18
                    numberOfQualifyingYears: 30
                    pensionSharingOrder: false
                    currentWeeklyPensionAmount: 155.65
                    reducedRateElection: false
                    statePensionAgeUnderConsideration: false
                    _links:
                      self:
                        href: /state-pension/pd/ni/QQ123456A
                RegularReducedRateElection:
                  description: Regular (Reduced Rate Election) response
                  value:
                    earningsIncludedUpTo: 2015-04-05
                    amounts:
                      protectedPayment: false
                      current:
                        weeklyAmount: 133.41
                        monthlyAmount: 580.1
                        annualAmount: 6961.14
                      forecast:
                        yearsToWork: 3
                        weeklyAmount: 146.76
                        monthlyAmount: 638.14
                        annualAmount: 7657.73
                      maximum:
                        yearsToWork: 3
                        gapsToFill: 2
                        weeklyAmount: 155.65
                        monthlyAmount: 676.8
                        annualAmount: 8121.59
                      cope:
                        weeklyAmount: 0
                        monthlyAmount: 0
                        annualAmount: 0
                      starting:
                        weeklyAmount: 130.05
                        monthlyAmount: 565.49
                        annualAmount: 6785.82
                      oldRules:
                        basicStatePension: 119.3
                        additionalStatePension: 10.75
                        graduatedRetirementBenefit: 0
                      newRules:
                        grossStatePension: 130.05
                        rebateDerivedAmount: 0
                    pensionAge: 64
                    pensionDate: 2018-07-06
                    finalRelevantYear: 2017-18
                    numberOfQualifyingYears: 30
                    pensionSharingOrder: false
                    currentWeeklyPensionAmount: 155.65
                    reducedRateElection: true
                    reducedRateElectionCurrentWeeklyAmount: 133.41
                    statePensionAgeUnderConsideration: false
                    _links:
                      self:
                        href: /state-pension/pd/ni/QQ123456A
                Exclusion:
                  description: Exclusion response
                  value:
                    exclusionReasons:
                      - AmountDissonance
                    pensionAge: 66
                    pensionDate: 2021-05-16
                    statePensionAgeUnderConsideration: false
                    _links:
                      self:
                        href: /state-pension/pd/ni/QQ123456A
        '400':
          description: 'Bad Request'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: ERROR_NINO_INVALID
              examples:
                InvalidNino:
                  description: Invalid NINO
                  value:
                    code: ERROR_NINO_INVALID
                BadRequest:
                  description: Bad Request
                  value:
                    code: BAD_REQUEST
        '401':
          description: 'Unauthorised'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: UNAUTHORIZED
              examples:
                Unauth:
                  description: Unauthorized
                  value:
                    code: UNAUTHORIZED
        '403':
          description: 'Forbidden'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: EXCLUSION_MANUAL_CORRESPONDENCE
              examples:
                ExcManCor:
                  description: Manual Correspondence exclusion, the customer cannot be served digitally and needs to contact HMRC
                  value:
                    code: EXCLUSION_MANUAL_CORRESPONDENCE
                ExcDead:
                  description: Death recorded, the customer needs to contact the National Insurance Helpline
                  value:
                    code: EXCLUSION_DEAD
                ExcCopePro:
                  description: Cope data has an open work item meaning that the customer cannot enter the service and must come back at a later date.
                  value:
                    code: EXCLUSION_COPE_PROCESSING
                ExcCopeProFail:
                  description: Cope data has a closed work item against it meaning that the customer cannot enter the service and is advised to contact DWP.
                  value:
                    code: EXCLUSION_COPE_PROCESSING_FAILED
        '404':
          description: 'Not Found'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: NOT_FOUND
              examples:
                NotFound:
                  description: Resource not found
                  value:
                    code: NOT_FOUND
        '406':
          description: 'Not Acceptable'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: ACCEPT_HEADER_INVALID
              examples:
                NotAcceptable:
                  description: Accept header is missing or invalid
                  value:
                    code: ACCEPT_HEADER_INVALID
        '500':
          description: 'Server Error'
          headers: {}
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
                  - example:
                      code: INTERNAL_SERVER_ERROR
              examples:
                InternalServerError:
                  description: Internal Server Error
                  value:
                    code: INTERNAL_SERVER_ERROR
      deprecated: false
      security:
        - User-Restricted:
            - read:state-pension
components:
  securitySchemes:
    User-Restricted:
      type:  oauth2
      description: HMRC supports OAuth 2.0 for authenticating User-restricted API requests
      flows:
        authorizationCode:
          authorizationUrl: https://api.service.hmrc.gov.uk/oauth/authorize
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          refreshUrl: https://api.service.hmrc.gov.uk/oauth/refresh
          scopes:
            read:state-pension: Access State Pension
  schemas:
    errorResponse:
      title: errorResponse
      required:
        - code
      type: object
      properties:
        code:
          type: string
    Amounts:
      title: Amounts
      type: object
      properties:
        protectedPayment:
          type: boolean
          description: Whether the customer has an amount higher than the full rate at the end of the 2015/16 tax year
          example: false
        current:
          $ref: '#/components/schemas/Current'
        forecast:
          $ref: '#/components/schemas/Forecast'
        maximum:
          $ref: '#/components/schemas/Maximum'
        cope:
          $ref: '#/components/schemas/Cope'
        starting:
          $ref: '#/components/schemas/Starting'
        oldRules:
          $ref: '#/components/schemas/OldRules'
        newRules:
          $ref: '#/components/schemas/NewRules'
    Cope:
      title: Cope
      type: object
      properties:
        weeklyAmount:
          type: number
          description: The amount of Contracted Out Pension Equivalent each week
          example: 0
        monthlyAmount:
          type: number
          description: The amount of Contracted Out Pension Equivalent every month
          example: 10.75
        annualAmount:
          type: number
          description: The amount of Contracted Out Pension Equivalent each year
          example: 0
    Current:
      title: Current
      type: object
      properties:
        weeklyAmount:
          type: number
          description: The amount of accrued State Pension to date each week
          example: 133.41
        monthlyAmount:
          type: number
          description: The amount of accrued State Pension to date each month
          example: 580.1
        annualAmount:
          type: number
          description: The amount of accrued State Pension to date each year
          example: 6961.14
    ExclusionReason:
      title: ExclusionReason
      enum:
        - IsleOfMan
      type: string
      description: The customer has National Insurance contributions from the Isle of Man. Manual separation of National Insurance record required, customer should contact the National Insurance Helpline.
    ExclusionReason1:
      title: ExclusionReason1
      enum:
        - AmountDissonance
      type: string
      description: Contention between amounts on internal systems. There is contention between the pension amounts in the internal systems, therefore a reliable forecast cannot be provided.
    ExclusionReason2:
      title: ExclusionReason2
      enum:
        - PostStatePensionAge
      type: string
      description: The current date is equal to or greater than the day before the customer’s State Pension date. The customer is eligible for State Pension and therefore we do not provide a forecast.
    Forecast:
      title: Forecast
      type: object
      properties:
        yearsToWork:
          type: number
          description: The number of future qualifying years needed to get the forecast amount
          example: 1
        weeklyAmount:
          type: number
          description: The forecasted amount of State Pension each week
          example: 146.76
        monthlyAmount:
          type: number
          description: The forecasted amount of State Pension each month
          example: 638.14
        annualAmount:
          type: number
          description: The forecasted amount of State Pension each year
          example: 7657.73
    Maximum:
      title: Maximum
      type: object
      properties:
        yearsToWork:
          type: number
          description: The number of future qualifying years needed to get the most amount possible after paying all gaps
          example: 3
        gapsToFill:
          type: number
          description: The total number of payable gaps - using this field may result in the customer filling more gaps than necessary
          example: 2
        weeklyAmount:
          type: number
          description: The maximum amount of State Pension each week
          example: 155.65
        monthlyAmount:
          type: number
          description: The maximum amount of State Pension each month
          example: 676.8
        annualAmount:
          type: number
          description: The maximum amount of State Pension each year
          example: 8121.59
    NewRules:
      title: NewRules
      type: object
      properties:
        grossStatePension:
          type: number
          description: The New Rules Basic Pension before any deductions
          example: 130.05
        rebateDerivedAmount:
          type: number
          description: The Rebate Derived Amount which gets deducted from Gross State Pension
          example: 0
    OldRules:
      title: OldRules
      type: object
      properties:
        basicStatePension:
          type: number
          description: The Old Rules Basic Pension before any additions
          example: 119.3
        additionalStatePension:
          type: number
          description: The earnings related pension on top of the Basic State Pension
          example: 10.75
        graduatedRetirementBenefit:
          type: number
          description: The benefit accrued when individuals paid NI contributions when ERB scheme was in operation between April 61 to April 75
          example: 0
    Starting:
      title: Starting
      type: object
      properties:
        weeklyAmount:
          type: number
          description: The starting amount of State Pension each week
          example: 130.05
        monthlyAmount:
          type: number
          description: The starting amount of State Pension every month
          example: 565.49
        annualAmount:
          type: number
          description: The starting amount of State Pension each year
          example: 6785.82
    StatePensionNiresponse:
      title: StatePensionNiresponse
      type: object
      properties:
        exclusionReasons:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/ExclusionReason'
              - $ref: '#/components/schemas/ExclusionReason1'
              - $ref: '#/components/schemas/ExclusionReason2'
          description: ''
        earningsIncludedUpTo:
          type: string
          description: The date which the calculations are based on. This is always the end date of the last posted tax year
          example: 2015-04-05
        amounts:
          $ref: '#/components/schemas/Amounts'
        pensionAge:
          type: number
          description: The customer’s age when they can claim State Pension
          example: 64
        pensionDate:
          type: string
          description: The date the customer can claim State Pension
          example: 2018-07-06
        finalRelevantYear:
          type: string
          description: The last full tax year before the customer’s State Pension date, for example 2017/18 with a date of 6 July 2018
          example: 2017-18
        numberOfQualifyingYears:
          type: number
          description: The number of qualifying years of National Insurance
          example: 30
        pensionSharingOrder:
          type: boolean
          description: Whether the customer has a ‘pension sharing order’ in effect
          example: true
        currentWeeklyPensionAmount:
          type: number
          description: The full rate of State Pension each week
          example: 155.65
        reducedRateElection:
          type: boolean
          description: Whether the customer has a ‘reduced rate election’ in force at the beginning of the tax year 35 years before the tax year of State Pension age
          example: true
        reducedRateElectionCurrentWeeklyAmount:
          type: number
          description: The amount of accrued State Pension to date each week returned only if the customer has ‘reduced rate election’ and regardless of qualifying years
          example: 133.41
        statePensionAgeUnderConsideration:
          type: boolean
          description: Whether the customer has a date of birth between 6 April 1970 and 5 April 1978.  These customers may have a change to their State Pension age due to an ongoing government consultation.
          example: true
        _links:
          title: Links
          type: object
          properties:
            self:
              title: Self
              type: object
              properties:
                href:
                  type: string
                  description: The relative url of the endpoint
                  example: /state-pension/ni/QQ123456A
      description: Regular Response
    StatePensionPdNiresponse:
      title: StatePensionPdNiresponse
      type: object
      properties:
        exclusionReasons:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/ExclusionReason'
              - $ref: '#/components/schemas/ExclusionReason1'
              - $ref: '#/components/schemas/ExclusionReason2'
          description: ''
        earningsIncludedUpTo:
          type: string
          description: The date which the calculations are based on. This is always the end date of the last posted tax year
          example: 2015-04-05
        amounts:
          $ref: '#/components/schemas/Amounts'
        pensionAge:
          type: number
          description: The customer’s age when they can claim State Pension
          example: 64
        pensionDate:
          type: string
          description: The date the customer can claim State Pension
          example: 2018-07-06
        finalRelevantYear:
          type: string
          description: The last full tax year before the customer’s State Pension date, for example 2017/18 with a date of 6 July 2018
          example: 2017-18
        numberOfQualifyingYears:
          type: number
          description: The number of qualifying years of National Insurance
          example: 30
        pensionSharingOrder:
          type: boolean
          description: Whether the customer has a ‘pension sharing order’ in effect
          example: true
        currentWeeklyPensionAmount:
          type: number
          description: The full rate of State Pension each week
          example: 155.65
        reducedRateElection:
          type: boolean
          description: Whether the customer has a ‘reduced rate election’ in force at the beginning of the tax year 35 years before the tax year of State Pension age
          example: true
        reducedRateElectionCurrentWeeklyAmount:
          type: number
          description: The amount of accrued State Pension to date each week returned only if the customer has ‘reduced rate election’ and regardless of qualifying years
          example: 133.41
        statePensionAgeUnderConsideration:
          type: boolean
          description: Whether the customer has a date of birth between 6 April 1970 and 5 April 1978.  These customers may have a change to their State Pension age due to an ongoing government consultation.
          example: true
        _links:
          title: Links
          type: object
          properties:
            self:
              title: Self
              type: object
              properties:
                href:
                  type: string
                  description: The relative url of the endpoint
                  example: /state-pension/ni/QQ123456A
      description: Regular Response
tags:
  - name: state-pension
    description: ''
